"""Generates the buildable ESP-IDF/PlatformIO project.

Everything emitted is plain, auditable C/C++ source (No-Binaries promise):
the model as a C array, a main.cc wired with a MicroMutableOpResolver that
registers only the ops this model actually uses, build files for both
ESP-IDF and PlatformIO, a README and a NOTICE.
"""

from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, FileSystemLoader, StrictUndefined

import fitchip
from fitchip.core.cal.backend import TargetProfile
from fitchip.core.inspector.base import ModelMeta

_TEMPLATES = Path(__file__).parent / "templates"

# PlatformIO board ids per FitChip target. New Espressif targets usually only
# need an entry here + a target YAML.
_PIO_BOARDS = {
    "esp32": "esp32dev",
    "esp32s3": "esp32-s3-devkitc-1",
    "esp32c3": "esp32-c3-devkitm-1",
}

# ESP-IDF chip name (idf.py set-target ...) per FitChip target.
_IDF_TARGETS = {
    "esp32": "esp32",
    "esp32s3": "esp32s3",
    "esp32c3": "esp32c3",
}


def generate_project(
    project_dir: Path,
    model_path: Path,
    meta: ModelMeta,
    target: TargetProfile,
    resolver_methods: list[str],
    arena_bytes: int,
    esp_nn_ops: list[str],
) -> None:
    env = Environment(
        loader=FileSystemLoader(_TEMPLATES),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
    )
    ctx = {
        "fitchip_version": fitchip.__version__,
        "project_name": f"fitchip_{target.id}_model",
        "target": target,
        "idf_target": _IDF_TARGETS.get(target.id, target.id),
        "pio_board": _PIO_BOARDS.get(target.id, "esp32dev"),
        "meta": meta,
        "resolver_methods": resolver_methods,
        "arena_bytes": _round_up(arena_bytes, 1024),
        "esp_nn_ops": esp_nn_ops,
        "model_len": meta.file_size_bytes,
        "quantized": bool(meta.is_quantized),
    }

    main_dir = project_dir / "main"
    main_dir.mkdir(parents=True, exist_ok=True)

    renders = {
        "CMakeLists.txt": "CMakeLists.txt.j2",
        "platformio.ini": "platformio.ini.j2",
        "sdkconfig.defaults": "sdkconfig.defaults.j2",
        "README.md": "README.md.j2",
        "NOTICE": "NOTICE.j2",
        "main/CMakeLists.txt": "main_CMakeLists.txt.j2",
        "main/idf_component.yml": "idf_component.yml.j2",
        "main/main.cc": "main.cc.j2",
        "main/model_data.h": "model_data.h.j2",
    }
    for out_name, template_name in renders.items():
        content = env.get_template(template_name).render(**ctx)
        (project_dir / out_name).write_text(content)

    _write_model_array(main_dir / "model_data.cc", model_path.read_bytes())


def _write_model_array(path: Path, data: bytes) -> None:
    """xxd-style C array. 16-byte aligned: TFLM requires an aligned model."""
    lines = [
        "// Generated by FitChip — the model flatbuffer as a C array.",
        '#include "model_data.h"',
        "",
        "alignas(16) const unsigned char g_model_data[] = {",
    ]
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines += [
        "};",
        f"const unsigned int g_model_data_len = {len(data)};",
        "",
    ]
    path.write_text("\n".join(lines))


def _round_up(value: int, multiple: int) -> int:
    return ((value + multiple - 1) // multiple) * multiple
