"""Generates the buildable CMake project around an ExecuTorch .pte.

Same No-Binaries promise as the TFLM backend: everything emitted is plain,
auditable source — the program as a C array, a minimal runner, a CMake
build that FetchContent-pins executorch, and an arm-none-eabi toolchain
file. FitChip deliberately does NOT pretend to generate complete STM32
firmware: startup code, linker script and HAL come from the user's BSP
(e.g. CubeMX); the README spells that out.
"""

from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, FileSystemLoader, StrictUndefined

import fitchip
from fitchip.core.cal.backend import TargetProfile
from fitchip.core.inspector.base import ModelMeta

_TEMPLATES = Path(__file__).parent / "templates"

# Pinned together with the `executorch` extra in pyproject.toml — bump both
# at once (API-churn guard, see the integration plan's risk list).
EXECUTORCH_GIT_TAG = "v0.4.0"

# arm-none-eabi-gcc flags per FitChip ISA name. A new Cortex-M target
# usually needs one entry here + a target YAML (mirror of TFLM's _IDF_TARGETS).
_CPU_FLAGS = {
    "cortex-m0plus": "-mcpu=cortex-m0plus -mfloat-abi=soft",
    "cortex-m3": "-mcpu=cortex-m3 -mfloat-abi=soft",
    "cortex-m4": "-mcpu=cortex-m4 -mfloat-abi=soft",
    "cortex-m4f": "-mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard",
    "cortex-m7": "-mcpu=cortex-m7 -mfpu=fpv5-d16 -mfloat-abi=hard",
    "cortex-m33": "-mcpu=cortex-m33 -mfpu=fpv5-sp-d16 -mfloat-abi=hard",
    "cortex-m55": "-mcpu=cortex-m55 -mfloat-abi=hard",
}

# Scratch pool for the runtime's method allocator (metadata, not activations).
METHOD_POOL_BYTES = 8 * 1024


def generate_project(
    project_dir: Path,
    pte_bytes: bytes,
    meta: ModelMeta,
    target: TargetProfile,
    arena_bytes: int,
    arena_exact: bool,
    cmsis_nn_ops: list[str],
    use_cmsis_nn: bool,
) -> None:
    env = Environment(
        loader=FileSystemLoader(_TEMPLATES),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
    )
    ctx = {
        "fitchip_version": fitchip.__version__,
        "project_name": f"fitchip_{target.id}_model",
        "target": target,
        "cpu_flags": _CPU_FLAGS.get(target.isa, f"-mcpu={target.isa}"),
        "executorch_tag": EXECUTORCH_GIT_TAG,
        "meta": meta,
        "arena_bytes": _round_up(arena_bytes, 1024),
        "arena_exact": arena_exact,
        "method_pool_bytes": METHOD_POOL_BYTES,
        "cmsis_nn_ops": cmsis_nn_ops,
        "use_cmsis_nn": use_cmsis_nn,
        "model_len": len(pte_bytes),
    }

    (project_dir / "cmake").mkdir(parents=True, exist_ok=True)
    renders = {
        "CMakeLists.txt": "CMakeLists.txt.j2",
        "cmake/arm-none-eabi.cmake": "arm-none-eabi.cmake.j2",
        "main.cpp": "main.cpp.j2",
        "model_pte.h": "model_pte.h.j2",
        "README.md": "README.md.j2",
        "NOTICE": "NOTICE.j2",
    }
    for out_name, template_name in renders.items():
        content = env.get_template(template_name).render(**ctx)
        (project_dir / out_name).write_text(content)

    _write_model_array(project_dir / "model_pte.c", pte_bytes)


def _write_model_array(path: Path, data: bytes) -> None:
    """xxd-style C array. 16-byte aligned: the runtime maps the program
    flatbuffer in place and requires aligned tensors."""
    lines = [
        "/* Generated by FitChip — the ExecuTorch program as a C array. */",
        '#include "model_pte.h"',
        "",
        "__attribute__((aligned(16))) const unsigned char g_model_pte[] = {",
    ]
    for offset in range(0, len(data), 12):
        chunk = data[offset : offset + 12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines += [
        "};",
        f"const unsigned int g_model_pte_len = {len(data)};",
        "",
    ]
    path.write_text("\n".join(lines))


def _round_up(value: int, multiple: int) -> int:
    return ((value + multiple - 1) // multiple) * multiple
